const js = require("@eslint/js");
const tseslint = require('typescript-eslint');

module.exports = [
    // Apply `eslint:recommended` manually
    js.configs.recommended,
    ...tseslint.configs.recommended,
    {
        files: ["lib/**/*.ts"],
        languageOptions: {
            ecmaVersion: 2020,
            sourceType: "module",
            globals: {},
        },
        linterOptions: {
            reportUnusedDisableDirectives: true,
        },
        rules: {
            indent: [
                "error",
                4,
                {
                    ignoreComments: true,
                    SwitchCase: 1
                }
            ],
            "linebreak-style": ["error", "unix"],
            "no-unmodified-loop-condition": "error",
            "no-use-before-define": "error",
            "require-atomic-updates": "error",
            "arrow-body-style": ["error", "as-needed"],
            "class-methods-use-this": "error",
            complexity: ["warn", 20],
            "default-case": "error",
            "default-case-last": "error",
            "dot-notation": ["error", { allowKeywords: true }],
            eqeqeq: "error",
            "id-denylist": ["error", "e", "cb", "callback", "tmp", "temporary"],
            "max-lines": ["warn", { "max": 1000, "skipBlankLines": true }],
            "max-classes-per-file": ["error", 2],
            "max-depth": ["warn", 5],
            "multiline-comment-style": ["error", "starred-block"],
            "max-statements": ["warn", 30],
            "no-alert": "error",
            "no-array-constructor": "error",
            "no-caller": "error",
            "no-confusing-arrow": "error",
            "no-console": ["error", { "allow": ["warn", "error"] }],
            "no-div-regex": "error",
            "no-eq-null": "error",
            "no-eval": "error",
            "no-extend-native": "error",
            "no-extra-bind": "error",
            "no-extra-label": "error",
            "no-extra-semi": "error",
            "no-floating-decimal": "error",
            "no-implicit-coercion": "off",
            "no-implied-eval": "error",
            "no-invalid-this": "error",
            "no-iterator": "error",
            "no-label-var": "error",
            "no-labels": "error",
            "no-lone-blocks": "error",
            "no-lonely-if": "error",
            "no-mixed-operators": "error",
            "no-multi-assign": "error",
            "no-multi-str": "error",
            "no-new-func": "error",
            "no-new-object": "error",
            "no-new-wrappers": "error",
            "no-octal-escape": "error",
            "no-proto": "error",
            "no-prototype-builtins": "off",
            "no-return-await": "error",
            "no-script-url": "error",
            "no-sequences": "error",
            "no-shadow": "error",
            "no-throw-literal": "error",
            "no-undef-init": "error",
            "no-underscore-dangle": ["error", { "allow": ["_id"] }],
            "no-unneeded-ternary": "error",
            "no-unused-expressions": "error",
            "no-useless-call": "error",
            "no-useless-computed-key": "error",
            "no-useless-concat": "error",
            "no-useless-constructor": "error",
            "no-useless-rename": "error",
            "no-useless-return": "error",
            "no-var": "error",
            "no-void": "error",
            "one-var": ["error", "never"],
            "one-var-declaration-per-line": ["error", "always"],
            "prefer-arrow-callback": "error",
            "prefer-const": "error",
            "prefer-promise-reject-errors": "error",
            "prefer-rest-params": "error",
            "prefer-spread": "error",
            "prefer-template": "off",
            "quote-props": ["error", "as-needed"],
            "spaced-comment": ["error", "always", { "line": { "markers": ["/"] } }],
            "yoda": ["error", "never"],
            "array-bracket-newline": ["error", "consistent"],
            "array-bracket-spacing": ["error", "never"],
            "array-element-newline": ["error", "consistent"],
            "arrow-parens": ["error", "as-needed"],
            "arrow-spacing": ["error", { "before": true, "after": true }],
            "block-spacing": "error",
            "brace-style": ["error", "1tbs", { "allowSingleLine": false }],
            "comma-dangle": ["error", {
                "arrays": "always-multiline",
                "objects": "always-multiline",
                "imports": "always-multiline",
                "exports": "never",
                "functions": "never"
            }],
            "comma-style": ["error", "last"],
            "computed-property-spacing": ["error", "never"],
            "dot-location": ["error", "property"],
            "func-call-spacing": ["error", "never"],
            "function-call-argument-newline": ["error", "consistent"],
            "implicit-arrow-linebreak": ["error", "beside"],
            "keyword-spacing": ["error", { "before": true, "after": true }],
            "lines-between-class-members": ["error", "always"],
            "max-len": ["error", { "code": 140 }],
            "max-statements-per-line": ["error", { "max": 1 }],
            "new-parens": ["error", "always"],
            "newline-per-chained-call": ["error", { "ignoreChainWithDepth": 5 }],
            "no-extra-parens": ["error", "all", { "nestedBinaryExpressions": false }],
            "no-multiple-empty-lines": ["error", { "max": 2, "maxEOF": 0 }],
            "no-whitespace-before-property": "error",
            "nonblock-statement-body-position": ["error", "beside"],
            "object-curly-spacing": ["error", "never"],
            "operator-linebreak": ["error", "after", { "overrides": { "?": "before", ":": "before" } }],
            "padded-blocks": ["error", { "blocks": "never", "classes": "always" }],
            "quotes": ["error", "single"],
            "rest-spread-spacing": ["error", "never"],
            "semi": ["error", "always"],
            "semi-spacing": ["error", { "before": false, "after": true }],
            "semi-style": ["error", "last"],
            "space-before-blocks": ["error", { "functions": "always", "keywords": "always", "classes": "always" }],
            "space-before-function-paren": ["error", "always"],
            "space-in-parens": ["error", "never"],
            "space-unary-ops": ["error", { "words": true, "nonwords": false }],
            "switch-colon-spacing": "error",
            "template-curly-spacing": ["error", "never"],
            "template-tag-spacing": ["error", "always"],
            "wrap-iife": ["error", "inside"],
            "yield-star-spacing": ["error", "before"],
            "@typescript-eslint/no-explicit-any": "off"
        },
    },
    {
        files: ["test/**/*.test.ts"],
        languageOptions: {
            ecmaVersion: 2020,
            sourceType: "module",
            globals: {},
        },
        linterOptions: {
            reportUnusedDisableDirectives: true,
        },
        rules: {
            "indent": [
                "error",
                4,
                {"ignoreComments": true, "SwitchCase": 1}
            ],
            "linebreak-style": [
                "error",
                "unix"
            ],
            "no-unmodified-loop-condition": "error",
            "no-use-before-define": "error",
            "require-atomic-updates": "error",
            "arrow-body-style": [
                "error",
                "as-needed"
            ],
            "class-methods-use-this": "error",
            "complexity": ["warn", 15],
            "default-case": "error",
            "default-case-last": "error",
            "dot-notation": ["error", {"allowKeywords": true}],
            "eqeqeq": "error",
            "id-denylist": ["error", "e", "cb", "callback", "tmp", "temporary"],
            "max-lines": ["warn", {"max": 1000, "skipBlankLines": true}],
            "max-classes-per-file": ["error", 2],
            "max-depth": ["warn", 5],
            "multiline-comment-style": ["error", "starred-block"],
            "max-statements": ["warn", 30],
            "no-alert": "error",
            "no-array-constructor": "error",
            "no-bitwise": "error",
            "no-caller": "error",
            "no-confusing-arrow": "error",
            "no-console": ["error", {"allow": ["warn", "error"]}],
            "no-div-regex": "error",
            "no-eq-null": "error",
            "no-eval": "error",
            "no-extend-native": "error",
            "no-extra-bind": "error",
            "no-extra-label": "error",
            "no-extra-semi": "error",
            "no-floating-decimal": "error",
            "no-implicit-coercion": ["error", {"allow": ["!!"]}],
            "no-implied-eval": "error",
            "no-invalid-this": "error",
            "no-iterator": "error",
            "no-label-var": "error",
            "no-labels": "error",
            "no-lone-blocks": "error",
            "no-lonely-if": "error",
            "no-mixed-operators": "error",
            "no-multi-assign": "error",
            "no-multi-str": "error",
            "no-new-func": "error",
            "no-new-object": "error",
            "no-new-wrappers": "error",
            "no-octal-escape": "error",
            "no-proto": "error",
            "no-prototype-builtins": "off",
            "no-return-await": "error",
            "no-script-url": "error",
            "no-sequences": "error",
            "no-shadow": "error",
            "no-throw-literal": "error",
            "no-undef-init": "error",
            "no-underscore-dangle": ["error", {"allow": ["_id"]}],
            "no-unneeded-ternary": "error",
            "no-unused-expressions": "error",
            "no-useless-call": "error",
            "no-useless-computed-key": "error",
            "no-useless-concat": "error",
            "no-useless-constructor": "error",
            "no-useless-rename": "error",
            "no-useless-return": "error",
            "no-var": "error",
            "no-void": "error",
            "one-var": ["error", "never"],
            "one-var-declaration-per-line": ["error", "always"],
            "prefer-arrow-callback": "error",
            "prefer-const": "error",
            "prefer-promise-reject-errors": "error",
            "prefer-rest-params": "error",
            "prefer-spread": "error",
            "prefer-template": "error",
            "quote-props": ["error", "as-needed"],
            "spaced-comment": ["error", "always", {"line": {"markers": ["/"]}}],
            "yoda": ["error", "never"],
            "array-bracket-newline": ["error", "consistent"],
            "array-bracket-spacing": ["error", "never"],
            "array-element-newline": ["error", "consistent"],
            "arrow-parens": ["error", "as-needed"],
            "arrow-spacing": ["error", {"before": true, "after": true}],
            "block-spacing": "error",
            "brace-style": ["error", "1tbs", {"allowSingleLine": false}],
            "comma-dangle": ["error", {
                "arrays": "always-multiline",
                "objects": "always-multiline",
                "imports": "always-multiline",
                "exports": "never",
                "functions": "never"
            }],
            "comma-style": ["error", "last"],
            "computed-property-spacing": ["error", "never"],
            "dot-location": ["error", "property"],
            "func-call-spacing": ["error", "never"],
            "function-call-argument-newline": ["error", "consistent"],
            "implicit-arrow-linebreak": ["error", "beside"],
            "keyword-spacing": ["error", {"before": true, "after": true}],
            "lines-between-class-members": ["error", "always"],
            "max-len": ["error", {"code": 140}],
            "max-statements-per-line": ["error", {"max": 1}],
            "new-parens": ["error", "always"],
            "newline-per-chained-call": ["error", {"ignoreChainWithDepth": 5}],
            "no-extra-parens": ["error", "all", {"nestedBinaryExpressions": false}],
            "no-multiple-empty-lines": ["error", {"max": 2, "maxEOF": 0}],
            "no-whitespace-before-property": "error",
            "nonblock-statement-body-position": ["error", "beside"],
            "object-curly-spacing": ["error", "never"],
            "operator-linebreak": ["error", "after", {"overrides": {"?": "before", ":": "before"}}],
            "padded-blocks": ["error", {"blocks": "never", "classes": "always"}],
            "quotes": ["error", "single"],
            "rest-spread-spacing": ["error", "never"],
            "semi": ["error", "always"],
            "semi-spacing": ["error", {"before": false, "after": true}],
            "semi-style": ["error", "last"],
            "space-before-blocks": ["error", {"functions": "always", "keywords": "always", "classes": "always"}],
            "space-before-function-paren": ["error", "always"],
            "space-in-parens": ["error", "never"],
            "space-unary-ops": ["error", {"words": true, "nonwords": false}],
            "switch-colon-spacing": "error",
            "template-curly-spacing": ["error", "never"],
            "template-tag-spacing": ["error", "always"],
            "wrap-iife": ["error", "inside"],
            "yield-star-spacing": ["error", "before"],
            "@typescript-eslint/no-explicit-any": "off",
            "@typescript-eslint/ban-ts-comment": "off"
        },
    },
];
